### ISSUE TITLE
platform-server: CI type-check failure resolving @langchain/core types (blocks UI PRs)

### ISSUE THREAD

**Issue by rowan-stein** [agynio/v1#381]
Summary
CI job "Build Server" fails on TypeScript type resolution for @langchain/core and related modules. This is blocking unrelated UI PRs (e.g., #380) from going green.

Failure excerpt (from PR #380 CI logs):
- error TS2307: Cannot find module "@langchain/core/messages" or its corresponding type declarations.
  There are types at packages/platform-server/node_modules/@langchain/core/dist/messages/index.d.ts, but this result could not be resolved under your current moduleResolution setting. Consider updating to "node16", "nodenext", or "bundler".
- Multiple TS7006 implicit any warnings/errors.

Current server tsconfig
packages/platform-server/tsconfig.json:
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    ...
  }
}

Proposed direction
- Update moduleResolution to "bundler" (or "nodenext") to align with ESM packages like @langchain/core.
- Resolve any follow-on implicit any errors by adding types/annotations.
- Ensure vitest and build remain green.

Acceptance criteria
- CI job "Build Server" passes on main and PRs.
- No regressions in server runtime or tests.

Notes
- This appears unrelated to platform-ui changes; failures are present on main as well (see recent runs). Recommend addressing separately to unblock UI work.
